/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_karlsland_m3g_AnimationController */

#ifndef _Included_org_karlsland_m3g_AnimationController
#define _Included_org_karlsland_m3g_AnimationController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_karlsland_m3g_AnimationController
 * Method:    jni_initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_AnimationController_jni_1initialize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_AnimationController
 * Method:    jni_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_AnimationController_jni_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_AnimationController
 * Method:    jni_getActiveIntervalEnd
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_AnimationController_jni_1getActiveIntervalEnd
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_AnimationController
 * Method:    jni_getActiveIntervalStart
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_AnimationController_jni_1getActiveIntervalStart
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_AnimationController
 * Method:    jni_getPosition
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_org_karlsland_m3g_AnimationController_jni_1getPosition
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_karlsland_m3g_AnimationController
 * Method:    jni_getRefWorldTime
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_AnimationController_jni_1getRefWorldTime
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_AnimationController
 * Method:    jni_getSpeed
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_karlsland_m3g_AnimationController_jni_1getSpeed
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_AnimationController
 * Method:    jni_getWeight
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_karlsland_m3g_AnimationController_jni_1getWeight
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_AnimationController
 * Method:    jni_setActiveInterval
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_AnimationController_jni_1setActiveInterval
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_karlsland_m3g_AnimationController
 * Method:    jni_setPosition
 * Signature: (FI)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_AnimationController_jni_1setPosition
  (JNIEnv *, jobject, jfloat, jint);

/*
 * Class:     org_karlsland_m3g_AnimationController
 * Method:    jni_setSpeed
 * Signature: (FI)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_AnimationController_jni_1setSpeed
  (JNIEnv *, jobject, jfloat, jint);

/*
 * Class:     org_karlsland_m3g_AnimationController
 * Method:    jni_setWeight
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_AnimationController_jni_1setWeight
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_karlsland_m3g_AnimationController
 * Method:    jni_print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_AnimationController_jni_1print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_karlsland_m3g_Mesh */

#ifndef _Included_org_karlsland_m3g_Mesh
#define _Included_org_karlsland_m3g_Mesh
#ifdef __cplusplus
extern "C" {
#endif
#undef org_karlsland_m3g_Mesh_NONE
#define org_karlsland_m3g_Mesh_NONE 144L
#undef org_karlsland_m3g_Mesh_ORIGIN
#define org_karlsland_m3g_Mesh_ORIGIN 145L
#undef org_karlsland_m3g_Mesh_X_AXIS
#define org_karlsland_m3g_Mesh_X_AXIS 146L
#undef org_karlsland_m3g_Mesh_Y_AXIS
#define org_karlsland_m3g_Mesh_Y_AXIS 147L
#undef org_karlsland_m3g_Mesh_Z_AXIS
#define org_karlsland_m3g_Mesh_Z_AXIS 148L
/*
 * Class:     org_karlsland_m3g_Mesh
 * Method:    jni_initialize
 * Signature: (Lorg/karlsland/m3g/VertexBuffer;[Lorg/karlsland/m3g/IndexBuffer;[Lorg/karlsland/m3g/Appearance;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Mesh_jni_1initialize__Lorg_karlsland_m3g_VertexBuffer_2_3Lorg_karlsland_m3g_IndexBuffer_2_3Lorg_karlsland_m3g_Appearance_2
  (JNIEnv *, jobject, jobject, jobjectArray, jobjectArray);

/*
 * Class:     org_karlsland_m3g_Mesh
 * Method:    jni_initialize
 * Signature: (Lorg/karlsland/m3g/VertexBuffer;Lorg/karlsland/m3g/IndexBuffer;Lorg/karlsland/m3g/Appearance;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Mesh_jni_1initialize__Lorg_karlsland_m3g_VertexBuffer_2Lorg_karlsland_m3g_IndexBuffer_2Lorg_karlsland_m3g_Appearance_2
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_Mesh
 * Method:    jni_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Mesh_jni_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Mesh
 * Method:    jni_getAppearance
 * Signature: (I)Lorg/karlsland/m3g/Appearance;
 */
JNIEXPORT jobject JNICALL Java_org_karlsland_m3g_Mesh_jni_1getAppearance
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_karlsland_m3g_Mesh
 * Method:    jni_getIndexBuffer
 * Signature: (I)Lorg/karlsland/m3g/IndexBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_karlsland_m3g_Mesh_jni_1getIndexBuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_karlsland_m3g_Mesh
 * Method:    jni_getSubmeshCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Mesh_jni_1getSubmeshCount
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Mesh
 * Method:    jni_getVertexBuffer
 * Signature: ()Lorg/karlsland/m3g/VertexBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_karlsland_m3g_Mesh_jni_1getVertexBuffer
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Mesh
 * Method:    jni_setAppearance
 * Signature: (ILorg/karlsland/m3g/Appearance;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Mesh_jni_1setAppearance
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_karlsland_m3g_Mesh
 * Method:    jni_print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Mesh_jni_1print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_karlsland_m3g_AnimationTrack */

#ifndef _Included_org_karlsland_m3g_AnimationTrack
#define _Included_org_karlsland_m3g_AnimationTrack
#ifdef __cplusplus
extern "C" {
#endif
#undef org_karlsland_m3g_AnimationTrack_ALPHA
#define org_karlsland_m3g_AnimationTrack_ALPHA 256L
#undef org_karlsland_m3g_AnimationTrack_AMBIENT_COLOR
#define org_karlsland_m3g_AnimationTrack_AMBIENT_COLOR 257L
#undef org_karlsland_m3g_AnimationTrack_COLOR
#define org_karlsland_m3g_AnimationTrack_COLOR 258L
#undef org_karlsland_m3g_AnimationTrack_CROP
#define org_karlsland_m3g_AnimationTrack_CROP 259L
#undef org_karlsland_m3g_AnimationTrack_DENSITY
#define org_karlsland_m3g_AnimationTrack_DENSITY 260L
#undef org_karlsland_m3g_AnimationTrack_DIFFUSE_COLOR
#define org_karlsland_m3g_AnimationTrack_DIFFUSE_COLOR 261L
#undef org_karlsland_m3g_AnimationTrack_EMISSIVE_COLOR
#define org_karlsland_m3g_AnimationTrack_EMISSIVE_COLOR 262L
#undef org_karlsland_m3g_AnimationTrack_FAR_DISTANCE
#define org_karlsland_m3g_AnimationTrack_FAR_DISTANCE 263L
#undef org_karlsland_m3g_AnimationTrack_FIELD_OF_VIEW
#define org_karlsland_m3g_AnimationTrack_FIELD_OF_VIEW 264L
#undef org_karlsland_m3g_AnimationTrack_INTENSITY
#define org_karlsland_m3g_AnimationTrack_INTENSITY 265L
#undef org_karlsland_m3g_AnimationTrack_MORPH_WEIGHTS
#define org_karlsland_m3g_AnimationTrack_MORPH_WEIGHTS 266L
#undef org_karlsland_m3g_AnimationTrack_NEAR_DISTANCE
#define org_karlsland_m3g_AnimationTrack_NEAR_DISTANCE 267L
#undef org_karlsland_m3g_AnimationTrack_ORIENTATION
#define org_karlsland_m3g_AnimationTrack_ORIENTATION 268L
#undef org_karlsland_m3g_AnimationTrack_PICKABILITY
#define org_karlsland_m3g_AnimationTrack_PICKABILITY 269L
#undef org_karlsland_m3g_AnimationTrack_SCALE
#define org_karlsland_m3g_AnimationTrack_SCALE 270L
#undef org_karlsland_m3g_AnimationTrack_SHININESS
#define org_karlsland_m3g_AnimationTrack_SHININESS 271L
#undef org_karlsland_m3g_AnimationTrack_SPECULAR_COLOR
#define org_karlsland_m3g_AnimationTrack_SPECULAR_COLOR 272L
#undef org_karlsland_m3g_AnimationTrack_SPOT_ANGLE
#define org_karlsland_m3g_AnimationTrack_SPOT_ANGLE 273L
#undef org_karlsland_m3g_AnimationTrack_SPOT_EXPONENT
#define org_karlsland_m3g_AnimationTrack_SPOT_EXPONENT 274L
#undef org_karlsland_m3g_AnimationTrack_TRANSLATION
#define org_karlsland_m3g_AnimationTrack_TRANSLATION 275L
#undef org_karlsland_m3g_AnimationTrack_VISIBILITY
#define org_karlsland_m3g_AnimationTrack_VISIBILITY 267L
/*
 * Class:     org_karlsland_m3g_AnimationTrack
 * Method:    jni_initialize
 * Signature: (Lorg/karlsland/m3g/KeyframeSequence;I)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_AnimationTrack_jni_1initialize
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     org_karlsland_m3g_AnimationTrack
 * Method:    jni_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_AnimationTrack_jni_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_AnimationTrack
 * Method:    jni_getController
 * Signature: ()Lorg/karlsland/m3g/AnimationController;
 */
JNIEXPORT jobject JNICALL Java_org_karlsland_m3g_AnimationTrack_jni_1getController
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_AnimationTrack
 * Method:    jni_getKeyframeSequence
 * Signature: ()Lorg/karlsland/m3g/KeyframeSequence;
 */
JNIEXPORT jobject JNICALL Java_org_karlsland_m3g_AnimationTrack_jni_1getKeyframeSequence
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_AnimationTrack
 * Method:    jni_getTargetProperty
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_AnimationTrack_jni_1getTargetProperty
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_AnimationTrack
 * Method:    jni_setController
 * Signature: (Lorg/karlsland/m3g/AnimationController;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_AnimationTrack_jni_1setController
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_AnimationTrack
 * Method:    jni_print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_AnimationTrack_jni_1print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_karlsland_m3g_MorphingMesh */

#ifndef _Included_org_karlsland_m3g_MorphingMesh
#define _Included_org_karlsland_m3g_MorphingMesh
#ifdef __cplusplus
extern "C" {
#endif
#undef org_karlsland_m3g_MorphingMesh_NONE
#define org_karlsland_m3g_MorphingMesh_NONE 144L
#undef org_karlsland_m3g_MorphingMesh_ORIGIN
#define org_karlsland_m3g_MorphingMesh_ORIGIN 145L
#undef org_karlsland_m3g_MorphingMesh_X_AXIS
#define org_karlsland_m3g_MorphingMesh_X_AXIS 146L
#undef org_karlsland_m3g_MorphingMesh_Y_AXIS
#define org_karlsland_m3g_MorphingMesh_Y_AXIS 147L
#undef org_karlsland_m3g_MorphingMesh_Z_AXIS
#define org_karlsland_m3g_MorphingMesh_Z_AXIS 148L
/*
 * Class:     org_karlsland_m3g_MorphingMesh
 * Method:    jni_initialize
 * Signature: (Lorg/karlsland/m3g/VertexBuffer;[Lorg/karlsland/m3g/VertexBuffer;[Lorg/karlsland/m3g/IndexBuffer;[Lorg/karlsland/m3g/Appearance;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_MorphingMesh_jni_1initialize__Lorg_karlsland_m3g_VertexBuffer_2_3Lorg_karlsland_m3g_VertexBuffer_2_3Lorg_karlsland_m3g_IndexBuffer_2_3Lorg_karlsland_m3g_Appearance_2
  (JNIEnv *, jobject, jobject, jobjectArray, jobjectArray, jobjectArray);

/*
 * Class:     org_karlsland_m3g_MorphingMesh
 * Method:    jni_initialize
 * Signature: (Lorg/karlsland/m3g/VertexBuffer;[Lorg/karlsland/m3g/VertexBuffer;Lorg/karlsland/m3g/IndexBuffer;Lorg/karlsland/m3g/Appearance;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_MorphingMesh_jni_1initialize__Lorg_karlsland_m3g_VertexBuffer_2_3Lorg_karlsland_m3g_VertexBuffer_2Lorg_karlsland_m3g_IndexBuffer_2Lorg_karlsland_m3g_Appearance_2
  (JNIEnv *, jobject, jobject, jobjectArray, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_MorphingMesh
 * Method:    jni_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_MorphingMesh_jni_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_MorphingMesh
 * Method:    jni_getMorphTarget
 * Signature: (I)Lorg/karlsland/m3g/IndexBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_karlsland_m3g_MorphingMesh_jni_1getMorphTarget
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_karlsland_m3g_MorphingMesh
 * Method:    jni_getMorphTargetCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_MorphingMesh_jni_1getMorphTargetCount
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_MorphingMesh
 * Method:    jni_getWeights
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_MorphingMesh_jni_1getWeights
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     org_karlsland_m3g_MorphingMesh
 * Method:    jni_setWeights
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_MorphingMesh_jni_1setWeights
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     org_karlsland_m3g_MorphingMesh
 * Method:    jni_print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_MorphingMesh_jni_1print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_karlsland_m3g_Appearance */

#ifndef _Included_org_karlsland_m3g_Appearance
#define _Included_org_karlsland_m3g_Appearance
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_karlsland_m3g_Appearance
 * Method:    jni_initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Appearance_jni_1initialize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Appearance
 * Method:    jni_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Appearance_jni_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Appearance
 * Method:    jni_getCompositingMode
 * Signature: ()Lorg/karlsland/m3g/CompositingMode;
 */
JNIEXPORT jobject JNICALL Java_org_karlsland_m3g_Appearance_jni_1getCompositingMode
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Appearance
 * Method:    jni_getFog
 * Signature: ()Lorg/karlsland/m3g/Fog;
 */
JNIEXPORT jobject JNICALL Java_org_karlsland_m3g_Appearance_jni_1getFog
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Appearance
 * Method:    jni_getLayer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Appearance_jni_1getLayer
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Appearance
 * Method:    jni_getMaterial
 * Signature: ()Lorg/karlsland/m3g/Material;
 */
JNIEXPORT jobject JNICALL Java_org_karlsland_m3g_Appearance_jni_1getMaterial
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Appearance
 * Method:    jni_getPolygonMode
 * Signature: ()Lorg/karlsland/m3g/PolygonMode;
 */
JNIEXPORT jobject JNICALL Java_org_karlsland_m3g_Appearance_jni_1getPolygonMode
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Appearance
 * Method:    jni_getTexture
 * Signature: (I)Lorg/karlsland/m3g/Texture2D;
 */
JNIEXPORT jobject JNICALL Java_org_karlsland_m3g_Appearance_jni_1getTexture
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_karlsland_m3g_Appearance
 * Method:    jni_setCompositingMode
 * Signature: (Lorg/karlsland/m3g/CompositingMode;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Appearance_jni_1setCompositingMode
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_Appearance
 * Method:    jni_setFog
 * Signature: (Lorg/karlsland/m3g/Fog;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Appearance_jni_1setFog
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_Appearance
 * Method:    jni_setLayer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Appearance_jni_1setLayer
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_karlsland_m3g_Appearance
 * Method:    jni_setMaterial
 * Signature: (Lorg/karlsland/m3g/Material;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Appearance_jni_1setMaterial
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_Appearance
 * Method:    jni_setPolygonMode
 * Signature: (Lorg/karlsland/m3g/PolygonMode;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Appearance_jni_1setPolygonMode
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_Appearance
 * Method:    jni_setTexture
 * Signature: (ILorg/karlsland/m3g/Texture2D;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Appearance_jni_1setTexture
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_karlsland_m3g_Appearance
 * Method:    jni_print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Appearance_jni_1print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_karlsland_m3g_Node */

#ifndef _Included_org_karlsland_m3g_Node
#define _Included_org_karlsland_m3g_Node
#ifdef __cplusplus
extern "C" {
#endif
#undef org_karlsland_m3g_Node_NONE
#define org_karlsland_m3g_Node_NONE 144L
#undef org_karlsland_m3g_Node_ORIGIN
#define org_karlsland_m3g_Node_ORIGIN 145L
#undef org_karlsland_m3g_Node_X_AXIS
#define org_karlsland_m3g_Node_X_AXIS 146L
#undef org_karlsland_m3g_Node_Y_AXIS
#define org_karlsland_m3g_Node_Y_AXIS 147L
#undef org_karlsland_m3g_Node_Z_AXIS
#define org_karlsland_m3g_Node_Z_AXIS 148L
/*
 * Class:     org_karlsland_m3g_Node
 * Method:    jni_initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Node_jni_1initialize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Node
 * Method:    jni_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Node_jni_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Node
 * Method:    jni_align
 * Signature: (Lorg/karlsland/m3g/Node;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Node_jni_1align
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_Node
 * Method:    jni_getAlignmentReference
 * Signature: (I)Lorg/karlsland/m3g/Node;
 */
JNIEXPORT jobject JNICALL Java_org_karlsland_m3g_Node_jni_1getAlignmentReference
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_karlsland_m3g_Node
 * Method:    jni_getAlignmentTarget
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Node_jni_1getAlignmentTarget
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_karlsland_m3g_Node
 * Method:    jni_getAlphaFactor
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_karlsland_m3g_Node_jni_1getAlphaFactor
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Node
 * Method:    jni_getParent
 * Signature: ()Lorg/karlsland/m3g/Node;
 */
JNIEXPORT jobject JNICALL Java_org_karlsland_m3g_Node_jni_1getParent
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Node
 * Method:    jni_getScope
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Node_jni_1getScope
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Node
 * Method:    jni_getTransformTo
 * Signature: (Lorg/karlsland/m3g/Node;Lorg/karlsland/m3g/Transform;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_karlsland_m3g_Node_jni_1getTransformTo
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_Node
 * Method:    jni_isPickingEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_karlsland_m3g_Node_jni_1isPickingEnabled
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Node
 * Method:    jni_isRenderingEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_karlsland_m3g_Node_jni_1isRenderingEnabled
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Node
 * Method:    jni_setAlignment
 * Signature: (Lorg/karlsland/m3g/Node;ILorg/karlsland/m3g/Node;I)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Node_jni_1setAlignment
  (JNIEnv *, jobject, jobject, jint, jobject, jint);

/*
 * Class:     org_karlsland_m3g_Node
 * Method:    jni_setAlphaFactor
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Node_jni_1setAlphaFactor
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_karlsland_m3g_Node
 * Method:    jni_setPickingEnable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Node_jni_1setPickingEnable
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_karlsland_m3g_Node
 * Method:    jni_setRenderingEnable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Node_jni_1setRenderingEnable
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_karlsland_m3g_Node
 * Method:    jni_setScope
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Node_jni_1setScope
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_karlsland_m3g_Node
 * Method:    jni_print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Node_jni_1print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_karlsland_m3g_Background */

#ifndef _Included_org_karlsland_m3g_Background
#define _Included_org_karlsland_m3g_Background
#ifdef __cplusplus
extern "C" {
#endif
#undef org_karlsland_m3g_Background_BORDER
#define org_karlsland_m3g_Background_BORDER 32L
#undef org_karlsland_m3g_Background_REPEAT
#define org_karlsland_m3g_Background_REPEAT 33L
/*
 * Class:     org_karlsland_m3g_Background
 * Method:    jni_initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Background_jni_1initialize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Background
 * Method:    jni_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Background_jni_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Background
 * Method:    jni_getColor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Background_jni_1getColor
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Background
 * Method:    jni_getCropHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Background_jni_1getCropHeight
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Background
 * Method:    jni_getCropWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Background_jni_1getCropWidth
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Background
 * Method:    jni_getCropX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Background_jni_1getCropX
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Background
 * Method:    jni_getCropY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Background_jni_1getCropY
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Background
 * Method:    jni_getImage
 * Signature: ()Lorg/karlsland/m3g/Image2D;
 */
JNIEXPORT jobject JNICALL Java_org_karlsland_m3g_Background_jni_1getImage
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Background
 * Method:    jni_getImageModeX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Background_jni_1getImageModeX
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Background
 * Method:    jni_getImageModeY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Background_jni_1getImageModeY
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Background
 * Method:    jni_isColorClearEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_karlsland_m3g_Background_jni_1isColorClearEnabled
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Background
 * Method:    jni_isDepthClearEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_karlsland_m3g_Background_jni_1isDepthClearEnabled
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Background
 * Method:    jni_setColor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Background_jni_1setColor
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_karlsland_m3g_Background
 * Method:    jni_setColorClearEnable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Background_jni_1setColorClearEnable
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_karlsland_m3g_Background
 * Method:    jni_setCrop
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Background_jni_1setCrop
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_karlsland_m3g_Background
 * Method:    jni_setDepthClearEnable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Background_jni_1setDepthClearEnable
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_karlsland_m3g_Background
 * Method:    jni_setImage
 * Signature: (Lorg/karlsland/m3g/Image2D;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Background_jni_1setImage
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_Background
 * Method:    jni_setImageMode
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Background_jni_1setImageMode
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_karlsland_m3g_Background
 * Method:    jni_print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Background_jni_1print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_karlsland_m3g_Object3D */

#ifndef _Included_org_karlsland_m3g_Object3D
#define _Included_org_karlsland_m3g_Object3D
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_karlsland_m3g_Object3D
 * Method:    jni_initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Object3D_jni_1initialize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Object3D
 * Method:    jni_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Object3D_jni_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Object3D
 * Method:    jni_addAnimationTrack
 * Signature: (Lorg/karlsland/m3g/AnimationTrack;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Object3D_jni_1addAnimationTrack
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_Object3D
 * Method:    jni_animate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Object3D_jni_1animate
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_karlsland_m3g_Object3D
 * Method:    jni_duplicate
 * Signature: ()Lorg/karlsland/m3g/Object3D;
 */
JNIEXPORT jobject JNICALL Java_org_karlsland_m3g_Object3D_jni_1duplicate
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Object3D
 * Method:    jni_find
 * Signature: (I)Lorg/karlsland/m3g/Object3D;
 */
JNIEXPORT jobject JNICALL Java_org_karlsland_m3g_Object3D_jni_1find
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_karlsland_m3g_Object3D
 * Method:    jni_getAnimationTrack
 * Signature: (I)Lorg/karlsland/m3g/AnimationTrack;
 */
JNIEXPORT jobject JNICALL Java_org_karlsland_m3g_Object3D_jni_1getAnimationTrack
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_karlsland_m3g_Object3D
 * Method:    jni_getAnimationTrackCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Object3D_jni_1getAnimationTrackCount
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Object3D
 * Method:    jni_getReferences
 * Signature: ([Lorg/karlsland/m3g/Object3D;)I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Object3D_jni_1getReferences
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     org_karlsland_m3g_Object3D
 * Method:    jni_getUserID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Object3D_jni_1getUserID
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Object3D
 * Method:    jni_getUserObject
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_karlsland_m3g_Object3D_jni_1getUserObject
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Object3D
 * Method:    jni_removeAnimationTrack
 * Signature: (Lorg/karlsland/m3g/AnimationTrack;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Object3D_jni_1removeAnimationTrack
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_Object3D
 * Method:    jni_setUserID
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Object3D_jni_1setUserID
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_karlsland_m3g_Object3D
 * Method:    jni_setUserObject
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Object3D_jni_1setUserObject
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_Object3D
 * Method:    jni_print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Object3D_jni_1print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_karlsland_m3g_Camera */

#ifndef _Included_org_karlsland_m3g_Camera
#define _Included_org_karlsland_m3g_Camera
#ifdef __cplusplus
extern "C" {
#endif
#undef org_karlsland_m3g_Camera_NONE
#define org_karlsland_m3g_Camera_NONE 144L
#undef org_karlsland_m3g_Camera_ORIGIN
#define org_karlsland_m3g_Camera_ORIGIN 145L
#undef org_karlsland_m3g_Camera_X_AXIS
#define org_karlsland_m3g_Camera_X_AXIS 146L
#undef org_karlsland_m3g_Camera_Y_AXIS
#define org_karlsland_m3g_Camera_Y_AXIS 147L
#undef org_karlsland_m3g_Camera_Z_AXIS
#define org_karlsland_m3g_Camera_Z_AXIS 148L
#undef org_karlsland_m3g_Camera_GENERIC
#define org_karlsland_m3g_Camera_GENERIC 48L
#undef org_karlsland_m3g_Camera_PARALLEL
#define org_karlsland_m3g_Camera_PARALLEL 49L
#undef org_karlsland_m3g_Camera_PERSPECTIVE
#define org_karlsland_m3g_Camera_PERSPECTIVE 50L
/*
 * Class:     org_karlsland_m3g_Camera
 * Method:    jni_initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Camera_jni_1initialize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Camera
 * Method:    jni_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Camera_jni_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Camera
 * Method:    jni_getProjection
 * Signature: ([F)I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Camera_jni_1getProjection___3F
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     org_karlsland_m3g_Camera
 * Method:    jni_getProjection
 * Signature: (Lorg/karlsland/m3g/Transform;)I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Camera_jni_1getProjection__Lorg_karlsland_m3g_Transform_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_Camera
 * Method:    jni_setGeneric
 * Signature: (Lorg/karlsland/m3g/Transform;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Camera_jni_1setGeneric
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_Camera
 * Method:    jni_setParallel
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Camera_jni_1setParallel
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_karlsland_m3g_Camera
 * Method:    jni_setPerspective
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Camera_jni_1setPerspective
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_karlsland_m3g_Camera
 * Method:    jni_print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Camera_jni_1print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_karlsland_m3g_PolygonMode */

#ifndef _Included_org_karlsland_m3g_PolygonMode
#define _Included_org_karlsland_m3g_PolygonMode
#ifdef __cplusplus
extern "C" {
#endif
#undef org_karlsland_m3g_PolygonMode_CULL_BACK
#define org_karlsland_m3g_PolygonMode_CULL_BACK 160L
#undef org_karlsland_m3g_PolygonMode_CULL_FRONT
#define org_karlsland_m3g_PolygonMode_CULL_FRONT 161L
#undef org_karlsland_m3g_PolygonMode_CULL_NONE
#define org_karlsland_m3g_PolygonMode_CULL_NONE 162L
#undef org_karlsland_m3g_PolygonMode_SHADE_FLAT
#define org_karlsland_m3g_PolygonMode_SHADE_FLAT 164L
#undef org_karlsland_m3g_PolygonMode_SHADE_SMOOTH
#define org_karlsland_m3g_PolygonMode_SHADE_SMOOTH 165L
#undef org_karlsland_m3g_PolygonMode_WINDING_CCW
#define org_karlsland_m3g_PolygonMode_WINDING_CCW 168L
#undef org_karlsland_m3g_PolygonMode_WINDING_CW
#define org_karlsland_m3g_PolygonMode_WINDING_CW 169L
/*
 * Class:     org_karlsland_m3g_PolygonMode
 * Method:    jni_initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_PolygonMode_jni_1initialize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_PolygonMode
 * Method:    jni_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_PolygonMode_jni_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_PolygonMode
 * Method:    jni_getCulling
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_PolygonMode_jni_1getCulling
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_PolygonMode
 * Method:    jni_getShading
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_PolygonMode_jni_1getShading
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_PolygonMode
 * Method:    jni_getWinding
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_PolygonMode_jni_1getWinding
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_PolygonMode
 * Method:    jni_isLocalCameraLightingEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_karlsland_m3g_PolygonMode_jni_1isLocalCameraLightingEnabled
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_PolygonMode
 * Method:    jni_isPerspectiveCorrectionEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_karlsland_m3g_PolygonMode_jni_1isPerspectiveCorrectionEnabled
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_PolygonMode
 * Method:    jni_isTwoSidedLightingEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_karlsland_m3g_PolygonMode_jni_1isTwoSidedLightingEnabled
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_PolygonMode
 * Method:    jni_setCulling
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_PolygonMode_jni_1setCulling
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_karlsland_m3g_PolygonMode
 * Method:    jni_setLocalCameraLightingEnable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_PolygonMode_jni_1setLocalCameraLightingEnable
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_karlsland_m3g_PolygonMode
 * Method:    jni_setPerspectiveCorrectionEnable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_PolygonMode_jni_1setPerspectiveCorrectionEnable
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_karlsland_m3g_PolygonMode
 * Method:    jni_setShading
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_PolygonMode_jni_1setShading
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_karlsland_m3g_PolygonMode
 * Method:    jni_setTwoSidedLightingEnable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_PolygonMode_jni_1setTwoSidedLightingEnable
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_karlsland_m3g_PolygonMode
 * Method:    jni_setWinding
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_PolygonMode_jni_1setWinding
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_karlsland_m3g_PolygonMode
 * Method:    jni_print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_PolygonMode_jni_1print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_karlsland_m3g_CompositingMode */

#ifndef _Included_org_karlsland_m3g_CompositingMode
#define _Included_org_karlsland_m3g_CompositingMode
#ifdef __cplusplus
extern "C" {
#endif
#undef org_karlsland_m3g_CompositingMode_ALPHA
#define org_karlsland_m3g_CompositingMode_ALPHA 64L
#undef org_karlsland_m3g_CompositingMode_ALPHA_ADD
#define org_karlsland_m3g_CompositingMode_ALPHA_ADD 65L
#undef org_karlsland_m3g_CompositingMode_MODULATE
#define org_karlsland_m3g_CompositingMode_MODULATE 66L
#undef org_karlsland_m3g_CompositingMode_MODULATE_X2
#define org_karlsland_m3g_CompositingMode_MODULATE_X2 67L
#undef org_karlsland_m3g_CompositingMode_REPLACE
#define org_karlsland_m3g_CompositingMode_REPLACE 68L
/*
 * Class:     org_karlsland_m3g_CompositingMode
 * Method:    jni_initialzie
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_CompositingMode_jni_1initialzie
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_CompositingMode
 * Method:    jni_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_CompositingMode_jni_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_CompositingMode
 * Method:    jni_getAlphaThreshold
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_karlsland_m3g_CompositingMode_jni_1getAlphaThreshold
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_CompositingMode
 * Method:    jni_getBlending
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_CompositingMode_jni_1getBlending
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_CompositingMode
 * Method:    jni_getDepthOffsetFactor
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_karlsland_m3g_CompositingMode_jni_1getDepthOffsetFactor
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_CompositingMode
 * Method:    jni_getDepthOffsetUnits
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_karlsland_m3g_CompositingMode_jni_1getDepthOffsetUnits
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_CompositingMode
 * Method:    jni_isAlphaWriteEnable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_karlsland_m3g_CompositingMode_jni_1isAlphaWriteEnable
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_CompositingMode
 * Method:    jni_isColorWriteEnable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_karlsland_m3g_CompositingMode_jni_1isColorWriteEnable
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_CompositingMode
 * Method:    jni_isDepthTestEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_karlsland_m3g_CompositingMode_jni_1isDepthTestEnabled
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_CompositingMode
 * Method:    jni_isDepthWriteEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_karlsland_m3g_CompositingMode_jni_1isDepthWriteEnabled
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_CompositingMode
 * Method:    jni_setAlphaThreshold
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_CompositingMode_jni_1setAlphaThreshold
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_karlsland_m3g_CompositingMode
 * Method:    jni_setAlphaWriteEnable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_CompositingMode_jni_1setAlphaWriteEnable
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_karlsland_m3g_CompositingMode
 * Method:    jni_setBlending
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_CompositingMode_jni_1setBlending
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_karlsland_m3g_CompositingMode
 * Method:    jni_setColorWriteEnable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_CompositingMode_jni_1setColorWriteEnable
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_karlsland_m3g_CompositingMode
 * Method:    jni_setDepthOffset
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_CompositingMode_jni_1setDepthOffset
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     org_karlsland_m3g_CompositingMode
 * Method:    jni_setDepthTestEnable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_CompositingMode_jni_1setDepthTestEnable
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_karlsland_m3g_CompositingMode
 * Method:    jni_setDepthWriteEnable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_CompositingMode_jni_1setDepthWriteEnable
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_karlsland_m3g_CompositingMode
 * Method:    jni_print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_CompositingMode_jni_1print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_karlsland_m3g_RayIntersection */

#ifndef _Included_org_karlsland_m3g_RayIntersection
#define _Included_org_karlsland_m3g_RayIntersection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_karlsland_m3g_RayIntersection
 * Method:    jni_initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_RayIntersection_jni_1initialize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_RayIntersection
 * Method:    jni_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_RayIntersection_jni_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_RayIntersection
 * Method:    jni_getDistance
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_karlsland_m3g_RayIntersection_jni_1getDistance
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_RayIntersection
 * Method:    jni_getIntersected
 * Signature: ()Lorg/karlsland/m3g/Node;
 */
JNIEXPORT jobject JNICALL Java_org_karlsland_m3g_RayIntersection_jni_1getIntersected
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_RayIntersection
 * Method:    jni_getNormalX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_karlsland_m3g_RayIntersection_jni_1getNormalX
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_RayIntersection
 * Method:    jni_getNormalY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_karlsland_m3g_RayIntersection_jni_1getNormalY
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_RayIntersection
 * Method:    jni_getNormalZ
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_karlsland_m3g_RayIntersection_jni_1getNormalZ
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_RayIntersection
 * Method:    jni_getRay
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_RayIntersection_jni_1getRay
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     org_karlsland_m3g_RayIntersection
 * Method:    jni_getSubmeshIndex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_RayIntersection_jni_1getSubmeshIndex
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_RayIntersection
 * Method:    jni_getTextureS
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_org_karlsland_m3g_RayIntersection_jni_1getTextureS
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_karlsland_m3g_RayIntersection
 * Method:    jni_getTextureT
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_org_karlsland_m3g_RayIntersection_jni_1getTextureT
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_karlsland_m3g_RayIntersection
 * Method:    jni_print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_RayIntersection_jni_1print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_karlsland_m3g_Fog */

#ifndef _Included_org_karlsland_m3g_Fog
#define _Included_org_karlsland_m3g_Fog
#ifdef __cplusplus
extern "C" {
#endif
#undef org_karlsland_m3g_Fog_EXPONENTIAL
#define org_karlsland_m3g_Fog_EXPONENTIAL 80L
#undef org_karlsland_m3g_Fog_LINEAR
#define org_karlsland_m3g_Fog_LINEAR 81L
/*
 * Class:     org_karlsland_m3g_Fog
 * Method:    jni_initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Fog_jni_1initialize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Fog
 * Method:    jni_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Fog_jni_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Fog
 * Method:    jni_getColor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Fog_jni_1getColor
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Fog
 * Method:    jni_getDensity
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_karlsland_m3g_Fog_jni_1getDensity
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Fog
 * Method:    jni_getFarDistance
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_karlsland_m3g_Fog_jni_1getFarDistance
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Fog
 * Method:    jni_getMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Fog_jni_1getMode
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Fog
 * Method:    jni_getNearDistance
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_karlsland_m3g_Fog_jni_1getNearDistance
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Fog
 * Method:    jni_setColor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Fog_jni_1setColor
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_karlsland_m3g_Fog
 * Method:    jni_setDensity
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Fog_jni_1setDensity
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_karlsland_m3g_Fog
 * Method:    jni_setLinear
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Fog_jni_1setLinear
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     org_karlsland_m3g_Fog
 * Method:    jni_setMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Fog_jni_1setMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_karlsland_m3g_Fog
 * Method:    jni_print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Fog_jni_1print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_karlsland_m3g_SkinnedMesh */

#ifndef _Included_org_karlsland_m3g_SkinnedMesh
#define _Included_org_karlsland_m3g_SkinnedMesh
#ifdef __cplusplus
extern "C" {
#endif
#undef org_karlsland_m3g_SkinnedMesh_NONE
#define org_karlsland_m3g_SkinnedMesh_NONE 144L
#undef org_karlsland_m3g_SkinnedMesh_ORIGIN
#define org_karlsland_m3g_SkinnedMesh_ORIGIN 145L
#undef org_karlsland_m3g_SkinnedMesh_X_AXIS
#define org_karlsland_m3g_SkinnedMesh_X_AXIS 146L
#undef org_karlsland_m3g_SkinnedMesh_Y_AXIS
#define org_karlsland_m3g_SkinnedMesh_Y_AXIS 147L
#undef org_karlsland_m3g_SkinnedMesh_Z_AXIS
#define org_karlsland_m3g_SkinnedMesh_Z_AXIS 148L
/*
 * Class:     org_karlsland_m3g_SkinnedMesh
 * Method:    jni_initialize
 * Signature: (Lorg/karlsland/m3g/VertexBuffer;[Lorg/karlsland/m3g/IndexBuffer;[Lorg/karlsland/m3g/Appearance;Lorg/karlsland/m3g/Group;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_SkinnedMesh_jni_1initialize__Lorg_karlsland_m3g_VertexBuffer_2_3Lorg_karlsland_m3g_IndexBuffer_2_3Lorg_karlsland_m3g_Appearance_2Lorg_karlsland_m3g_Group_2
  (JNIEnv *, jobject, jobject, jobjectArray, jobjectArray, jobject);

/*
 * Class:     org_karlsland_m3g_SkinnedMesh
 * Method:    jni_initialize
 * Signature: (Lorg/karlsland/m3g/VertexBuffer;Lorg/karlsland/m3g/IndexBuffer;Lorg/karlsland/m3g/Appearance;Lorg/karlsland/m3g/Group;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_SkinnedMesh_jni_1initialize__Lorg_karlsland_m3g_VertexBuffer_2Lorg_karlsland_m3g_IndexBuffer_2Lorg_karlsland_m3g_Appearance_2Lorg_karlsland_m3g_Group_2
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_SkinnedMesh
 * Method:    jni_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_SkinnedMesh_jni_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_SkinnedMesh
 * Method:    jni_addTransform
 * Signature: (Lorg/karlsland/m3g/Node;III)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_SkinnedMesh_jni_1addTransform
  (JNIEnv *, jobject, jobject, jint, jint, jint);

/*
 * Class:     org_karlsland_m3g_SkinnedMesh
 * Method:    jni_getBoneTransform
 * Signature: (Lorg/karlsland/m3g/Node;Lorg/karlsland/m3g/Transform;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_SkinnedMesh_jni_1getBoneTransform
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_SkinnedMesh
 * Method:    jni_getBoneVertices
 * Signature: (Lorg/karlsland/m3g/Node;[I[F)I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_SkinnedMesh_jni_1getBoneVertices
  (JNIEnv *, jobject, jobject, jintArray, jfloatArray);

/*
 * Class:     org_karlsland_m3g_SkinnedMesh
 * Method:    jni_getSkeleton
 * Signature: ()Lorg/karlsland/m3g/Group;
 */
JNIEXPORT jobject JNICALL Java_org_karlsland_m3g_SkinnedMesh_jni_1getSkeleton
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_SkinnedMesh
 * Method:    jni_print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_SkinnedMesh_jni_1print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_karlsland_m3g_Graphics3D */

#ifndef _Included_org_karlsland_m3g_Graphics3D
#define _Included_org_karlsland_m3g_Graphics3D
#ifdef __cplusplus
extern "C" {
#endif
#undef org_karlsland_m3g_Graphics3D_ANTIALIAS
#define org_karlsland_m3g_Graphics3D_ANTIALIAS 2L
#undef org_karlsland_m3g_Graphics3D_DITHER
#define org_karlsland_m3g_Graphics3D_DITHER 4L
#undef org_karlsland_m3g_Graphics3D_OVERWRITE
#define org_karlsland_m3g_Graphics3D_OVERWRITE 16L
#undef org_karlsland_m3g_Graphics3D_TRUE_COLOR
#define org_karlsland_m3g_Graphics3D_TRUE_COLOR 8L
/*
 * Class:     org_karlsland_m3g_Graphics3D
 * Method:    jni_initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Graphics3D_jni_1initialize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Graphics3D
 * Method:    jni_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Graphics3D_jni_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Graphics3D
 * Method:    jni_addLight
 * Signature: (Lorg/karlsland/m3g/Light;Lorg/karlsland/m3g/Transform;)I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Graphics3D_jni_1addLight
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_Graphics3D
 * Method:    jni_bindTarget
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Graphics3D_jni_1bindTarget__Ljava_lang_Object_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_Graphics3D
 * Method:    jni_bindTarget
 * Signature: (Ljava/lang/Object;ZI)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Graphics3D_jni_1bindTarget__Ljava_lang_Object_2ZI
  (JNIEnv *, jobject, jobject, jboolean, jint);

/*
 * Class:     org_karlsland_m3g_Graphics3D
 * Method:    jni_clear
 * Signature: (Lorg/karlsland/m3g/Background;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Graphics3D_jni_1clear
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_Graphics3D
 * Method:    jni_getCamera
 * Signature: (Lorg/karlsland/m3g/Transform;)Lorg/karlsland/m3g/Camera;
 */
JNIEXPORT jobject JNICALL Java_org_karlsland_m3g_Graphics3D_jni_1getCamera
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_Graphics3D
 * Method:    jni_getDepthRangeFar
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_karlsland_m3g_Graphics3D_jni_1getDepthRangeFar
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Graphics3D
 * Method:    jni_getDepthRangeNear
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_karlsland_m3g_Graphics3D_jni_1getDepthRangeNear
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Graphics3D
 * Method:    jni_getHints
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Graphics3D_jni_1getHints
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Graphics3D
 * Method:    jni_getInstance
 * Signature: ()Lorg/karlsland/m3g/Graphics3D;
 */
JNIEXPORT jobject JNICALL Java_org_karlsland_m3g_Graphics3D_jni_1getInstance
  (JNIEnv *, jclass);

/*
 * Class:     org_karlsland_m3g_Graphics3D
 * Method:    jni_getLight
 * Signature: (ILorg/karlsland/m3g/Transform;)Lorg/karlsland/m3g/Light;
 */
JNIEXPORT jobject JNICALL Java_org_karlsland_m3g_Graphics3D_jni_1getLight
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_karlsland_m3g_Graphics3D
 * Method:    jni_getLightCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Graphics3D_jni_1getLightCount
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Graphics3D
 * Method:    jni_getProperties
 * Signature: ()Ljava/util/Hashtable;
 */
JNIEXPORT jobject JNICALL Java_org_karlsland_m3g_Graphics3D_jni_1getProperties
  (JNIEnv *, jclass);

/*
 * Class:     org_karlsland_m3g_Graphics3D
 * Method:    jni_getTarget
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_karlsland_m3g_Graphics3D_jni_1getTarget
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Graphics3D
 * Method:    jni_getViewportHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Graphics3D_jni_1getViewportHeight
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Graphics3D
 * Method:    jni_getViewportWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Graphics3D_jni_1getViewportWidth
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Graphics3D
 * Method:    jni_getViewportX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Graphics3D_jni_1getViewportX
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Graphics3D
 * Method:    jni_getViewportY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Graphics3D_jni_1getViewportY
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Graphics3D
 * Method:    jni_isDepthBufferEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_karlsland_m3g_Graphics3D_jni_1isDepthBufferEnabled
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Graphics3D
 * Method:    jni_releaseTarget
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Graphics3D_jni_1releaseTarget
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Graphics3D
 * Method:    jni_render
 * Signature: (Lorg/karlsland/m3g/Node;Lorg/karlsland/m3g/Transform;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Graphics3D_jni_1render__Lorg_karlsland_m3g_Node_2Lorg_karlsland_m3g_Transform_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_Graphics3D
 * Method:    jni_render
 * Signature: (Lorg/karlsland/m3g/VertexBuffer;Lorg/karlsland/m3g/IndexBuffer;Lorg/karlsland/m3g/Appearance;Lorg/karlsland/m3g/Transform;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Graphics3D_jni_1render__Lorg_karlsland_m3g_VertexBuffer_2Lorg_karlsland_m3g_IndexBuffer_2Lorg_karlsland_m3g_Appearance_2Lorg_karlsland_m3g_Transform_2
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_Graphics3D
 * Method:    jni_render
 * Signature: (Lorg/karlsland/m3g/VertexBuffer;Lorg/karlsland/m3g/IndexBuffer;Lorg/karlsland/m3g/Appearance;Lorg/karlsland/m3g/Transform;I)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Graphics3D_jni_1render__Lorg_karlsland_m3g_VertexBuffer_2Lorg_karlsland_m3g_IndexBuffer_2Lorg_karlsland_m3g_Appearance_2Lorg_karlsland_m3g_Transform_2I
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     org_karlsland_m3g_Graphics3D
 * Method:    jni_render
 * Signature: (Lorg/karlsland/m3g/World;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Graphics3D_jni_1render__Lorg_karlsland_m3g_World_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_Graphics3D
 * Method:    jni_resetLights
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Graphics3D_jni_1resetLights
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Graphics3D
 * Method:    jni_setCamera
 * Signature: (Lorg/karlsland/m3g/Camera;Lorg/karlsland/m3g/Transform;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Graphics3D_jni_1setCamera
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_Graphics3D
 * Method:    jni_setDepthRange
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Graphics3D_jni_1setDepthRange
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     org_karlsland_m3g_Graphics3D
 * Method:    jni_setLight
 * Signature: (ILorg/karlsland/m3g/Light;Lorg/karlsland/m3g/Transform;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Graphics3D_jni_1setLight
  (JNIEnv *, jobject, jint, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_Graphics3D
 * Method:    jni_setViewport
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Graphics3D_jni_1setViewport
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_karlsland_m3g_Graphics3D
 * Method:    jni_print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Graphics3D_jni_1print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_karlsland_m3g_Sprite3D */

#ifndef _Included_org_karlsland_m3g_Sprite3D
#define _Included_org_karlsland_m3g_Sprite3D
#ifdef __cplusplus
extern "C" {
#endif
#undef org_karlsland_m3g_Sprite3D_NONE
#define org_karlsland_m3g_Sprite3D_NONE 144L
#undef org_karlsland_m3g_Sprite3D_ORIGIN
#define org_karlsland_m3g_Sprite3D_ORIGIN 145L
#undef org_karlsland_m3g_Sprite3D_X_AXIS
#define org_karlsland_m3g_Sprite3D_X_AXIS 146L
#undef org_karlsland_m3g_Sprite3D_Y_AXIS
#define org_karlsland_m3g_Sprite3D_Y_AXIS 147L
#undef org_karlsland_m3g_Sprite3D_Z_AXIS
#define org_karlsland_m3g_Sprite3D_Z_AXIS 148L
/*
 * Class:     org_karlsland_m3g_Sprite3D
 * Method:    jni_initialize
 * Signature: (ZLorg/karlsland/m3g/Image2D;Lorg/karlsland/m3g/Appearance;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Sprite3D_jni_1initialize
  (JNIEnv *, jobject, jboolean, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_Sprite3D
 * Method:    jni_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Sprite3D_jni_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Sprite3D
 * Method:    jni_getAppearance
 * Signature: ()Lorg/karlsland/m3g/Appearance;
 */
JNIEXPORT jobject JNICALL Java_org_karlsland_m3g_Sprite3D_jni_1getAppearance
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Sprite3D
 * Method:    jni_getCropHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Sprite3D_jni_1getCropHeight
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Sprite3D
 * Method:    jni_getCropWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Sprite3D_jni_1getCropWidth
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Sprite3D
 * Method:    jni_getCropX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Sprite3D_jni_1getCropX
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Sprite3D
 * Method:    jni_getCropY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Sprite3D_jni_1getCropY
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Sprite3D
 * Method:    jni_getImage
 * Signature: ()Lorg/karlsland/m3g/Image2D;
 */
JNIEXPORT jobject JNICALL Java_org_karlsland_m3g_Sprite3D_jni_1getImage
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Sprite3D
 * Method:    jni_isScaled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_karlsland_m3g_Sprite3D_jni_1isScaled
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Sprite3D
 * Method:    jni_setAppearance
 * Signature: (Lorg/karlsland/m3g/Appearance;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Sprite3D_jni_1setAppearance
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_Sprite3D
 * Method:    jni_setCrop
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Sprite3D_jni_1setCrop
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_karlsland_m3g_Sprite3D
 * Method:    jni_setImage
 * Signature: (Lorg/karlsland/m3g/Image2D;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Sprite3D_jni_1setImage
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_Sprite3D
 * Method:    jni_print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Sprite3D_jni_1print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_karlsland_m3g_Group */

#ifndef _Included_org_karlsland_m3g_Group
#define _Included_org_karlsland_m3g_Group
#ifdef __cplusplus
extern "C" {
#endif
#undef org_karlsland_m3g_Group_NONE
#define org_karlsland_m3g_Group_NONE 144L
#undef org_karlsland_m3g_Group_ORIGIN
#define org_karlsland_m3g_Group_ORIGIN 145L
#undef org_karlsland_m3g_Group_X_AXIS
#define org_karlsland_m3g_Group_X_AXIS 146L
#undef org_karlsland_m3g_Group_Y_AXIS
#define org_karlsland_m3g_Group_Y_AXIS 147L
#undef org_karlsland_m3g_Group_Z_AXIS
#define org_karlsland_m3g_Group_Z_AXIS 148L
/*
 * Class:     org_karlsland_m3g_Group
 * Method:    jni_initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Group_jni_1initialize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Group
 * Method:    jni_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Group_jni_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Group
 * Method:    jni_addChild
 * Signature: (Lorg/karlsland/m3g/Node;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Group_jni_1addChild
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_Group
 * Method:    jni_getChild
 * Signature: (I)Lorg/karlsland/m3g/Node;
 */
JNIEXPORT jobject JNICALL Java_org_karlsland_m3g_Group_jni_1getChild
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_karlsland_m3g_Group
 * Method:    jni_getChildCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Group_jni_1getChildCount
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Group
 * Method:    jni_pick
 * Signature: (IFFLorg/karlsland/m3g/Camera;Lorg/karlsland/m3g/RayIntersection;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_karlsland_m3g_Group_jni_1pick__IFFLorg_karlsland_m3g_Camera_2Lorg_karlsland_m3g_RayIntersection_2
  (JNIEnv *, jobject, jint, jfloat, jfloat, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_Group
 * Method:    jni_pick
 * Signature: (IFFFFFLorg/karlsland/m3g/RayIntersection;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_karlsland_m3g_Group_jni_1pick__IFFFFFLorg_karlsland_m3g_RayIntersection_2
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jobject);

/*
 * Class:     org_karlsland_m3g_Group
 * Method:    jni_removeChild
 * Signature: (Lorg/karlsland/m3g/Node;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Group_jni_1removeChild
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_Group
 * Method:    jni_print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Group_jni_1print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_karlsland_m3g_Texture2D */

#ifndef _Included_org_karlsland_m3g_Texture2D
#define _Included_org_karlsland_m3g_Texture2D
#ifdef __cplusplus
extern "C" {
#endif
#undef org_karlsland_m3g_Texture2D_FILTER_BASE_LEVEL
#define org_karlsland_m3g_Texture2D_FILTER_BASE_LEVEL 208L
#undef org_karlsland_m3g_Texture2D_FILTER_LINEAR
#define org_karlsland_m3g_Texture2D_FILTER_LINEAR 209L
#undef org_karlsland_m3g_Texture2D_FILTER_NEAREST
#define org_karlsland_m3g_Texture2D_FILTER_NEAREST 210L
#undef org_karlsland_m3g_Texture2D_FUNC_ADD
#define org_karlsland_m3g_Texture2D_FUNC_ADD 224L
#undef org_karlsland_m3g_Texture2D_FUNC_BLEND
#define org_karlsland_m3g_Texture2D_FUNC_BLEND 225L
#undef org_karlsland_m3g_Texture2D_FUNC_DECAL
#define org_karlsland_m3g_Texture2D_FUNC_DECAL 226L
#undef org_karlsland_m3g_Texture2D_FUNC_MODULATE
#define org_karlsland_m3g_Texture2D_FUNC_MODULATE 227L
#undef org_karlsland_m3g_Texture2D_FUNC_REPLACE
#define org_karlsland_m3g_Texture2D_FUNC_REPLACE 228L
#undef org_karlsland_m3g_Texture2D_WRAP_CLAMP
#define org_karlsland_m3g_Texture2D_WRAP_CLAMP 240L
#undef org_karlsland_m3g_Texture2D_WRAP_REPEAT
#define org_karlsland_m3g_Texture2D_WRAP_REPEAT 241L
/*
 * Class:     org_karlsland_m3g_Texture2D
 * Method:    jni_initialize
 * Signature: (Lorg/karlsland/m3g/Image2D;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Texture2D_jni_1initialize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_Texture2D
 * Method:    jni_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Texture2D_jni_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Texture2D
 * Method:    jni_getBlendColor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Texture2D_jni_1getBlendColor
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Texture2D
 * Method:    jni_getBlending
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Texture2D_jni_1getBlending
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Texture2D
 * Method:    jni_getImage
 * Signature: ()Lorg/karlsland/m3g/Image2D;
 */
JNIEXPORT jobject JNICALL Java_org_karlsland_m3g_Texture2D_jni_1getImage
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Texture2D
 * Method:    jni_getImageFilter
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Texture2D_jni_1getImageFilter
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Texture2D
 * Method:    jni_getLevelFilter
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Texture2D_jni_1getLevelFilter
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Texture2D
 * Method:    jni_getWrappingS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Texture2D_jni_1getWrappingS
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Texture2D
 * Method:    jni_getWrappingT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Texture2D_jni_1getWrappingT
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Texture2D
 * Method:    jni_setBlendColor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Texture2D_jni_1setBlendColor
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_karlsland_m3g_Texture2D
 * Method:    jni_setBlending
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Texture2D_jni_1setBlending
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_karlsland_m3g_Texture2D
 * Method:    jni_setFiltering
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Texture2D_jni_1setFiltering
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_karlsland_m3g_Texture2D
 * Method:    jni_setImage
 * Signature: (Lorg/karlsland/m3g/Image2D;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Texture2D_jni_1setImage
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_Texture2D
 * Method:    jni_setWrapping
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Texture2D_jni_1setWrapping
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_karlsland_m3g_Texture2D
 * Method:    jni_print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Texture2D_jni_1print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_karlsland_m3g_Image2D */

#ifndef _Included_org_karlsland_m3g_Image2D
#define _Included_org_karlsland_m3g_Image2D
#ifdef __cplusplus
extern "C" {
#endif
#undef org_karlsland_m3g_Image2D_ALPHA
#define org_karlsland_m3g_Image2D_ALPHA 96L
#undef org_karlsland_m3g_Image2D_LUMINANCE
#define org_karlsland_m3g_Image2D_LUMINANCE 97L
#undef org_karlsland_m3g_Image2D_LUMINANCE_ALPHA
#define org_karlsland_m3g_Image2D_LUMINANCE_ALPHA 98L
#undef org_karlsland_m3g_Image2D_RGB
#define org_karlsland_m3g_Image2D_RGB 99L
#undef org_karlsland_m3g_Image2D_RGBA
#define org_karlsland_m3g_Image2D_RGBA 100L
/*
 * Class:     org_karlsland_m3g_Image2D
 * Method:    jni_initialize
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Image2D_jni_1initialize__III
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_karlsland_m3g_Image2D
 * Method:    jni_initialize
 * Signature: (III[B)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Image2D_jni_1initialize__III_3B
  (JNIEnv *, jobject, jint, jint, jint, jbyteArray);

/*
 * Class:     org_karlsland_m3g_Image2D
 * Method:    jni_initialize
 * Signature: (III[B[B)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Image2D_jni_1initialize__III_3B_3B
  (JNIEnv *, jobject, jint, jint, jint, jbyteArray, jbyteArray);

/*
 * Class:     org_karlsland_m3g_Image2D
 * Method:    jni_initialize
 * Signature: (ILjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Image2D_jni_1initialize__ILjava_lang_Object_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_karlsland_m3g_Image2D
 * Method:    jni_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Image2D_jni_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Image2D
 * Method:    jni_getFormat
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Image2D_jni_1getFormat
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Image2D
 * Method:    jni_getHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Image2D_jni_1getHeight
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Image2D
 * Method:    jni_getWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Image2D_jni_1getWidth
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Image2D
 * Method:    jni_isMutable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_karlsland_m3g_Image2D_jni_1isMutable
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Image2D
 * Method:    jni_set
 * Signature: (IIII[B)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Image2D_jni_1set
  (JNIEnv *, jobject, jint, jint, jint, jint, jbyteArray);

/*
 * Class:     org_karlsland_m3g_Image2D
 * Method:    jni_print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Image2D_jni_1print
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Image2D
 * Method:    jni_writePng
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Image2D_jni_1writePng
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_karlsland_m3g_Transform */

#ifndef _Included_org_karlsland_m3g_Transform
#define _Included_org_karlsland_m3g_Transform
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_karlsland_m3g_Transform
 * Method:    jni_initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Transform_jni_1initialize__
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Transform
 * Method:    jni_initialize
 * Signature: (Lorg/karlsland/m3g/Transform;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Transform_jni_1initialize__Lorg_karlsland_m3g_Transform_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_Transform
 * Method:    jni_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Transform_jni_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Transform
 * Method:    jni_get
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Transform_jni_1get
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     org_karlsland_m3g_Transform
 * Method:    jni_invert
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Transform_jni_1invert
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Transform
 * Method:    jni_postMultiply
 * Signature: (Lorg/karlsland/m3g/Transform;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Transform_jni_1postMultiply
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_Transform
 * Method:    jni_postRotate
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Transform_jni_1postRotate
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_karlsland_m3g_Transform
 * Method:    jni_postRotateQuat
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Transform_jni_1postRotateQuat
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_karlsland_m3g_Transform
 * Method:    jni_postScale
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Transform_jni_1postScale
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     org_karlsland_m3g_Transform
 * Method:    jni_postTranslate
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Transform_jni_1postTranslate
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     org_karlsland_m3g_Transform
 * Method:    jni_set
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Transform_jni_1set___3F
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     org_karlsland_m3g_Transform
 * Method:    jni_set
 * Signature: (Lorg/karlsland/m3g/Transform;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Transform_jni_1set__Lorg_karlsland_m3g_Transform_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_Transform
 * Method:    jni_setIdentity
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Transform_jni_1setIdentity
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Transform
 * Method:    jni_transform
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Transform_jni_1transform___3F
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     org_karlsland_m3g_Transform
 * Method:    jni_transform
 * Signature: (Lorg/karlsland/m3g/VertexArray;[FZ)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Transform_jni_1transform__Lorg_karlsland_m3g_VertexArray_2_3FZ
  (JNIEnv *, jobject, jobject, jfloatArray, jboolean);

/*
 * Class:     org_karlsland_m3g_Transform
 * Method:    jni_transpose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Transform_jni_1transpose
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Transform
 * Method:    jni_print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Transform_jni_1print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_karlsland_m3g_IndexBuffer */

#ifndef _Included_org_karlsland_m3g_IndexBuffer
#define _Included_org_karlsland_m3g_IndexBuffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_karlsland_m3g_IndexBuffer
 * Method:    jni_initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_IndexBuffer_jni_1initialize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_IndexBuffer
 * Method:    jni_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_IndexBuffer_jni_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_IndexBuffer
 * Method:    jni_getIndexCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_IndexBuffer_jni_1getIndexCount
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_IndexBuffer
 * Method:    jni_getIndices
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_IndexBuffer_jni_1getIndices
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     org_karlsland_m3g_IndexBuffer
 * Method:    jni_print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_IndexBuffer_jni_1print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_karlsland_m3g_Transformable */

#ifndef _Included_org_karlsland_m3g_Transformable
#define _Included_org_karlsland_m3g_Transformable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_karlsland_m3g_Transformable
 * Method:    jni_initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Transformable_jni_1initialize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Transformable
 * Method:    jni_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Transformable_jni_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Transformable
 * Method:    jni_getCompositeTransform
 * Signature: (Lorg/karlsland/m3g/Transform;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Transformable_jni_1getCompositeTransform
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_Transformable
 * Method:    jni_getOrientation
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Transformable_jni_1getOrientation
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     org_karlsland_m3g_Transformable
 * Method:    jni_getScale
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Transformable_jni_1getScale
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     org_karlsland_m3g_Transformable
 * Method:    jni_getTransform
 * Signature: (Lorg/karlsland/m3g/Transform;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Transformable_jni_1getTransform
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_Transformable
 * Method:    jni_getTranslation
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Transformable_jni_1getTranslation
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     org_karlsland_m3g_Transformable
 * Method:    jni_postRotate
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Transformable_jni_1postRotate
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_karlsland_m3g_Transformable
 * Method:    jni_preRotate
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Transformable_jni_1preRotate
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_karlsland_m3g_Transformable
 * Method:    jni_scale
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Transformable_jni_1scale
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     org_karlsland_m3g_Transformable
 * Method:    jni_setOrientation
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Transformable_jni_1setOrientation
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_karlsland_m3g_Transformable
 * Method:    jni_setScale
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Transformable_jni_1setScale
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     org_karlsland_m3g_Transformable
 * Method:    jni_setTransform
 * Signature: (Lorg/karlsland/m3g/Transform;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Transformable_jni_1setTransform
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_Transformable
 * Method:    jni_setTranslation
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Transformable_jni_1setTranslation
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     org_karlsland_m3g_Transformable
 * Method:    jni_translate
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Transformable_jni_1translate
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     org_karlsland_m3g_Transformable
 * Method:    jni_print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Transformable_jni_1print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_karlsland_m3g_KeyframeSequence */

#ifndef _Included_org_karlsland_m3g_KeyframeSequence
#define _Included_org_karlsland_m3g_KeyframeSequence
#ifdef __cplusplus
extern "C" {
#endif
#undef org_karlsland_m3g_KeyframeSequence_CONSTANT
#define org_karlsland_m3g_KeyframeSequence_CONSTANT 192L
#undef org_karlsland_m3g_KeyframeSequence_LINEAR
#define org_karlsland_m3g_KeyframeSequence_LINEAR 176L
#undef org_karlsland_m3g_KeyframeSequence_LOOP
#define org_karlsland_m3g_KeyframeSequence_LOOP 193L
#undef org_karlsland_m3g_KeyframeSequence_SLERP
#define org_karlsland_m3g_KeyframeSequence_SLERP 177L
#undef org_karlsland_m3g_KeyframeSequence_SPLINE
#define org_karlsland_m3g_KeyframeSequence_SPLINE 178L
#undef org_karlsland_m3g_KeyframeSequence_SQUAD
#define org_karlsland_m3g_KeyframeSequence_SQUAD 179L
#undef org_karlsland_m3g_KeyframeSequence_STEP
#define org_karlsland_m3g_KeyframeSequence_STEP 180L
/*
 * Class:     org_karlsland_m3g_KeyframeSequence
 * Method:    jni_initialize
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_KeyframeSequence_jni_1initialize
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_karlsland_m3g_KeyframeSequence
 * Method:    jni_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_KeyframeSequence_jni_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_KeyframeSequence
 * Method:    jni_getComponentCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_KeyframeSequence_jni_1getComponentCount
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_KeyframeSequence
 * Method:    jni_getDuration
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_KeyframeSequence_jni_1getDuration
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_KeyframeSequence
 * Method:    jni_getInterpolationType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_KeyframeSequence_jni_1getInterpolationType
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_KeyframeSequence
 * Method:    jni_getKeyframe
 * Signature: (I[F)I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_KeyframeSequence_jni_1getKeyframe
  (JNIEnv *, jobject, jint, jfloatArray);

/*
 * Class:     org_karlsland_m3g_KeyframeSequence
 * Method:    jni_getKeyframeCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_KeyframeSequence_jni_1getKeyframeCount
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_KeyframeSequence
 * Method:    jni_getRepeatMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_KeyframeSequence_jni_1getRepeatMode
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_KeyframeSequence
 * Method:    jni_getValidRangeFirst
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_KeyframeSequence_jni_1getValidRangeFirst
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_KeyframeSequence
 * Method:    jni_getValidRangeLast
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_KeyframeSequence_jni_1getValidRangeLast
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_KeyframeSequence
 * Method:    jni_setDuration
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_KeyframeSequence_jni_1setDuration
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_karlsland_m3g_KeyframeSequence
 * Method:    jni_setKeyframe
 * Signature: (II[F)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_KeyframeSequence_jni_1setKeyframe
  (JNIEnv *, jobject, jint, jint, jfloatArray);

/*
 * Class:     org_karlsland_m3g_KeyframeSequence
 * Method:    jni_setRepeatMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_KeyframeSequence_jni_1setRepeatMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_karlsland_m3g_KeyframeSequence
 * Method:    jni_setValidRange
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_KeyframeSequence_jni_1setValidRange
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_karlsland_m3g_KeyframeSequence
 * Method:    jni_print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_KeyframeSequence_jni_1print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_karlsland_m3g_TriangleStripArray */

#ifndef _Included_org_karlsland_m3g_TriangleStripArray
#define _Included_org_karlsland_m3g_TriangleStripArray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_karlsland_m3g_TriangleStripArray
 * Method:    jni_initialize
 * Signature: ([I[I)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_TriangleStripArray_jni_1initialize___3I_3I
  (JNIEnv *, jobject, jintArray, jintArray);

/*
 * Class:     org_karlsland_m3g_TriangleStripArray
 * Method:    jni_initialize
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_TriangleStripArray_jni_1initialize__I_3I
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     org_karlsland_m3g_TriangleStripArray
 * Method:    jni_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_TriangleStripArray_jni_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_TriangleStripArray
 * Method:    jni_print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_TriangleStripArray_jni_1print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_karlsland_m3g_Light */

#ifndef _Included_org_karlsland_m3g_Light
#define _Included_org_karlsland_m3g_Light
#ifdef __cplusplus
extern "C" {
#endif
#undef org_karlsland_m3g_Light_AMBIENT
#define org_karlsland_m3g_Light_AMBIENT 128L
#undef org_karlsland_m3g_Light_DIRECTIONAL
#define org_karlsland_m3g_Light_DIRECTIONAL 129L
#undef org_karlsland_m3g_Light_OMNI
#define org_karlsland_m3g_Light_OMNI 130L
#undef org_karlsland_m3g_Light_SPOT
#define org_karlsland_m3g_Light_SPOT 131L
/*
 * Class:     org_karlsland_m3g_Light
 * Method:    jni_initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Light_jni_1initialize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Light
 * Method:    jni_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Light_jni_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Light
 * Method:    jni_getColor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Light_jni_1getColor
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Light
 * Method:    jni_getConstantAttenuation
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_karlsland_m3g_Light_jni_1getConstantAttenuation
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Light
 * Method:    jni_getIntensity
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_karlsland_m3g_Light_jni_1getIntensity
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Light
 * Method:    jni_getLinearAttenuation
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_karlsland_m3g_Light_jni_1getLinearAttenuation
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Light
 * Method:    jni_getMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Light_jni_1getMode
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Light
 * Method:    jni_getQuadraticAttenuation
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_karlsland_m3g_Light_jni_1getQuadraticAttenuation
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Light
 * Method:    jni_getSpotAngle
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_karlsland_m3g_Light_jni_1getSpotAngle
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Light
 * Method:    jni_getSpotExponent
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_karlsland_m3g_Light_jni_1getSpotExponent
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Light
 * Method:    jni_setAttenuation
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Light_jni_1setAttenuation
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     org_karlsland_m3g_Light
 * Method:    jni_setColor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Light_jni_1setColor
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_karlsland_m3g_Light
 * Method:    jni_setIntensity
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Light_jni_1setIntensity
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_karlsland_m3g_Light
 * Method:    jni_setMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Light_jni_1setMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_karlsland_m3g_Light
 * Method:    jni_setSpotAngle
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Light_jni_1setSpotAngle
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_karlsland_m3g_Light
 * Method:    jni_setSpotExponent
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Light_jni_1setSpotExponent
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_karlsland_m3g_Light
 * Method:    jni_print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Light_jni_1print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_karlsland_m3g_VertexArray */

#ifndef _Included_org_karlsland_m3g_VertexArray
#define _Included_org_karlsland_m3g_VertexArray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_karlsland_m3g_VertexArray
 * Method:    jni_initialize
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_VertexArray_jni_1initialize
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_karlsland_m3g_VertexArray
 * Method:    jni_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_VertexArray_jni_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_VertexArray
 * Method:    jni_get
 * Signature: (II[B)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_VertexArray_jni_1get__II_3B
  (JNIEnv *, jobject, jint, jint, jbyteArray);

/*
 * Class:     org_karlsland_m3g_VertexArray
 * Method:    jni_get
 * Signature: (II[S)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_VertexArray_jni_1get__II_3S
  (JNIEnv *, jobject, jint, jint, jshortArray);

/*
 * Class:     org_karlsland_m3g_VertexArray
 * Method:    jni_get
 * Signature: (II[F)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_VertexArray_jni_1get__II_3F
  (JNIEnv *, jobject, jint, jint, jfloatArray);

/*
 * Class:     org_karlsland_m3g_VertexArray
 * Method:    jni_getComponentCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_VertexArray_jni_1getComponentCount
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_VertexArray
 * Method:    jni_getComponentType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_VertexArray_jni_1getComponentType
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_VertexArray
 * Method:    jni_getVertexCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_VertexArray_jni_1getVertexCount
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_VertexArray
 * Method:    jni_set
 * Signature: (II[B)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_VertexArray_jni_1set__II_3B
  (JNIEnv *, jobject, jint, jint, jbyteArray);

/*
 * Class:     org_karlsland_m3g_VertexArray
 * Method:    jni_set
 * Signature: (II[S)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_VertexArray_jni_1set__II_3S
  (JNIEnv *, jobject, jint, jint, jshortArray);

/*
 * Class:     org_karlsland_m3g_VertexArray
 * Method:    jni_set
 * Signature: (II[F)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_VertexArray_jni_1set__II_3F
  (JNIEnv *, jobject, jint, jint, jfloatArray);

/*
 * Class:     org_karlsland_m3g_VertexArray
 * Method:    jni_print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_VertexArray_jni_1print
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_VertexArray
 * Method:    jni_print_raw_data
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_VertexArray_jni_1print_1raw_1data
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_karlsland_m3g_Loader */

#ifndef _Included_org_karlsland_m3g_Loader
#define _Included_org_karlsland_m3g_Loader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_karlsland_m3g_Loader
 * Method:    jni_load
 * Signature: ([BI)[Lorg/karlsland/m3g/Object3D;
 */
JNIEXPORT jobjectArray JNICALL Java_org_karlsland_m3g_Loader_jni_1load___3BI
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     org_karlsland_m3g_Loader
 * Method:    jni_load
 * Signature: (Ljava/lang/String;)[Lorg/karlsland/m3g/Object3D;
 */
JNIEXPORT jobjectArray JNICALL Java_org_karlsland_m3g_Loader_jni_1load__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_karlsland_m3g_VertexBuffer */

#ifndef _Included_org_karlsland_m3g_VertexBuffer
#define _Included_org_karlsland_m3g_VertexBuffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_karlsland_m3g_VertexBuffer
 * Method:    jni_initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_VertexBuffer_jni_1initialize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_VertexBuffer
 * Method:    jni_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_VertexBuffer_jni_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_VertexBuffer
 * Method:    jni_getColors
 * Signature: ()Lorg/karlsland/m3g/VertexArray;
 */
JNIEXPORT jobject JNICALL Java_org_karlsland_m3g_VertexBuffer_jni_1getColors
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_VertexBuffer
 * Method:    jni_getDefaultColor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_VertexBuffer_jni_1getDefaultColor
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_VertexBuffer
 * Method:    jni_getNormals
 * Signature: ()Lorg/karlsland/m3g/VertexArray;
 */
JNIEXPORT jobject JNICALL Java_org_karlsland_m3g_VertexBuffer_jni_1getNormals
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_VertexBuffer
 * Method:    jni_getPositions
 * Signature: ([F)Lorg/karlsland/m3g/VertexArray;
 */
JNIEXPORT jobject JNICALL Java_org_karlsland_m3g_VertexBuffer_jni_1getPositions
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     org_karlsland_m3g_VertexBuffer
 * Method:    jni_getTexCoords
 * Signature: (I[F)Lorg/karlsland/m3g/VertexArray;
 */
JNIEXPORT jobject JNICALL Java_org_karlsland_m3g_VertexBuffer_jni_1getTexCoords
  (JNIEnv *, jobject, jint, jfloatArray);

/*
 * Class:     org_karlsland_m3g_VertexBuffer
 * Method:    jni_getVertexCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_VertexBuffer_jni_1getVertexCount
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_VertexBuffer
 * Method:    jni_setColors
 * Signature: (Lorg/karlsland/m3g/VertexArray;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_VertexBuffer_jni_1setColors
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_VertexBuffer
 * Method:    jni_setDefaultColor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_VertexBuffer_jni_1setDefaultColor
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_karlsland_m3g_VertexBuffer
 * Method:    jni_setNormals
 * Signature: (Lorg/karlsland/m3g/VertexArray;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_VertexBuffer_jni_1setNormals
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_VertexBuffer
 * Method:    jni_setPositions
 * Signature: (Lorg/karlsland/m3g/VertexArray;F[F)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_VertexBuffer_jni_1setPositions
  (JNIEnv *, jobject, jobject, jfloat, jfloatArray);

/*
 * Class:     org_karlsland_m3g_VertexBuffer
 * Method:    jni_setTexCoords
 * Signature: (ILorg/karlsland/m3g/VertexArray;F[F)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_VertexBuffer_jni_1setTexCoords
  (JNIEnv *, jobject, jint, jobject, jfloat, jfloatArray);

/*
 * Class:     org_karlsland_m3g_VertexBuffer
 * Method:    jni_print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_VertexBuffer_jni_1print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_karlsland_m3g_Material */

#ifndef _Included_org_karlsland_m3g_Material
#define _Included_org_karlsland_m3g_Material
#ifdef __cplusplus
extern "C" {
#endif
#undef org_karlsland_m3g_Material_AMBIENT
#define org_karlsland_m3g_Material_AMBIENT 1024L
#undef org_karlsland_m3g_Material_DIFFUSE
#define org_karlsland_m3g_Material_DIFFUSE 2048L
#undef org_karlsland_m3g_Material_EMISSIVE
#define org_karlsland_m3g_Material_EMISSIVE 4096L
#undef org_karlsland_m3g_Material_SPECULAR
#define org_karlsland_m3g_Material_SPECULAR 8192L
/*
 * Class:     org_karlsland_m3g_Material
 * Method:    jni_initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Material_jni_1initialize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Material
 * Method:    jni_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Material_jni_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Material
 * Method:    jni_getColor
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_karlsland_m3g_Material_jni_1getColor
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_karlsland_m3g_Material
 * Method:    jni_getShininess
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_karlsland_m3g_Material_jni_1getShininess
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Material
 * Method:    jni_isVertexColorTrackingEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_karlsland_m3g_Material_jni_1isVertexColorTrackingEnabled
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_Material
 * Method:    jni_setColor
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Material_jni_1setColor
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_karlsland_m3g_Material
 * Method:    jni_setShininess
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Material_jni_1setShininess
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_karlsland_m3g_Material
 * Method:    jni_setVertexColorTrackingEnable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Material_jni_1setVertexColorTrackingEnable
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_karlsland_m3g_Material
 * Method:    jni_print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_Material_jni_1print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_karlsland_m3g_World */

#ifndef _Included_org_karlsland_m3g_World
#define _Included_org_karlsland_m3g_World
#ifdef __cplusplus
extern "C" {
#endif
#undef org_karlsland_m3g_World_NONE
#define org_karlsland_m3g_World_NONE 144L
#undef org_karlsland_m3g_World_ORIGIN
#define org_karlsland_m3g_World_ORIGIN 145L
#undef org_karlsland_m3g_World_X_AXIS
#define org_karlsland_m3g_World_X_AXIS 146L
#undef org_karlsland_m3g_World_Y_AXIS
#define org_karlsland_m3g_World_Y_AXIS 147L
#undef org_karlsland_m3g_World_Z_AXIS
#define org_karlsland_m3g_World_Z_AXIS 148L
/*
 * Class:     org_karlsland_m3g_World
 * Method:    jni_initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_World_jni_1initialize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_World
 * Method:    jni_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_World_jni_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_World
 * Method:    jni_getActiveCamera
 * Signature: ()Lorg/karlsland/m3g/Camera;
 */
JNIEXPORT jobject JNICALL Java_org_karlsland_m3g_World_jni_1getActiveCamera
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_World
 * Method:    jni_getBackground
 * Signature: ()Lorg/karlsland/m3g/Background;
 */
JNIEXPORT jobject JNICALL Java_org_karlsland_m3g_World_jni_1getBackground
  (JNIEnv *, jobject);

/*
 * Class:     org_karlsland_m3g_World
 * Method:    jni_setActiveCamera
 * Signature: (Lorg/karlsland/m3g/Camera;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_World_jni_1setActiveCamera
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_World
 * Method:    jni_setBackground
 * Signature: (Lorg/karlsland/m3g/Background;)V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_World_jni_1setBackground
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_karlsland_m3g_World
 * Method:    jni_print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_karlsland_m3g_World_jni_1print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
