/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AnimationController */

#ifndef _Included_AnimationController
#define _Included_AnimationController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AnimationController
 * Method:    jni_initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AnimationController_jni_1initialize
  (JNIEnv *, jobject);

/*
 * Class:     AnimationController
 * Method:    jni_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AnimationController_jni_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     AnimationController
 * Method:    jni_getActiveIntervalEnd
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_AnimationController_jni_1getActiveIntervalEnd
  (JNIEnv *, jobject);

/*
 * Class:     AnimationController
 * Method:    jni_getActiveIntervalStart
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_AnimationController_jni_1getActiveIntervalStart
  (JNIEnv *, jobject);

/*
 * Class:     AnimationController
 * Method:    jni_getPosition
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_AnimationController_jni_1getPosition
  (JNIEnv *, jobject);

/*
 * Class:     AnimationController
 * Method:    jni_getRefWorldTime
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_AnimationController_jni_1getRefWorldTime
  (JNIEnv *, jobject);

/*
 * Class:     AnimationController
 * Method:    jni_getSpeed
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_AnimationController_jni_1getSpeed
  (JNIEnv *, jobject);

/*
 * Class:     AnimationController
 * Method:    jni_getWeight
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_AnimationController_jni_1getWeight
  (JNIEnv *, jobject);

/*
 * Class:     AnimationController
 * Method:    jni_setActiveInterval
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_AnimationController_jni_1setActiveInterval
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     AnimationController
 * Method:    jni_setPosition
 * Signature: (FI)V
 */
JNIEXPORT void JNICALL Java_AnimationController_jni_1setPosition
  (JNIEnv *, jobject, jfloat, jint);

/*
 * Class:     AnimationController
 * Method:    jni_setSpeed
 * Signature: (FI)V
 */
JNIEXPORT void JNICALL Java_AnimationController_jni_1setSpeed
  (JNIEnv *, jobject, jfloat, jint);

/*
 * Class:     AnimationController
 * Method:    jni_setWeight
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_AnimationController_jni_1setWeight
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
